# Wave Makefile — the lifecycle only: help / build / test / lint / ci /
# publish / clean. Anything else is the `fluxor` CLI directly
# (`fluxor modules build`, `fluxor run`, `fluxor update`, `fluxor sync`,
# `fluxor build --check …`) — a make target that merely renames one CLI
# command is bloat, not convenience.
#
# The bodies are gate-enforced character for character by `fluxor ci`'s
# `makefile` phase (../standards/make.md §2). They can be identical across
# projects because the VERB is not: each reads this checkout's shape — no root
# `Cargo.toml`, `modules/` + `[ci].targets`, the `tests/harness` sub-workspace,
# the declared module harnesses, `[ci.test] scripts` — and does what that shape
# implies. `make help` is generated by `fluxor help --make`, which walks
# `tools/` for real, so the script list cannot fall behind the tree.
#
# Shadow-tracked `tests/` and `examples/` (../standards/test-tracking.md) are
# not targets either — `git shadow status` / `git shadow log` are one command
# each, and the staging incantation lives in README.md where a reader without
# the CLI installed can still find it.

SHELL       := /bin/bash
.SHELLFLAGS := -euo pipefail -c

.DEFAULT_GOAL := build

.PHONY: help build test lint ci publish clean

help:
	@fluxor help --make

build:
	fluxor build

test:
	fluxor test

lint:
	fluxor lint

ci:
	fluxor ci

publish:
	fluxor publish

clean:
	fluxor clean
