#!/usr/bin/env bash
# The connection envelope, generated from the constants that compile it.
#
# Every ceiling on the connection path is a compiled constant owned by its
# own layer, and the effective envelope is whichever is smallest on the path:
# the http manifest's slot table says 256 on a Pi 5, and the TLS session
# table in front of it holds 64. This script reads each constant from the
# synced SDK profile (every transport ceiling, TLS sessions and QUIC
# connections included) and from Wave's own sources, renders
# `docs/reference/envelope.md`, and in check mode fails when the committed
# document disagrees — so the table a reader consults cannot drift from the
# constant the module compiled.
#
# Usage: tools/ci/envelope_table.sh            # check: fail on drift
#        tools/ci/envelope_table.sh --write    # regenerate the document
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SDK="$ROOT/target/fluxor/fluxor-abi/sdk/abi/config.rs"
DOC="$ROOT/docs/reference/envelope.md"
MODE="${1:-}"

if [[ ! -f "$SDK" ]]; then
  echo "envelope_table: $SDK missing — run \`fluxor sync\` (or any module build) first" >&2
  exit 1
fi

# const NAME: usize = N; inside the `mod profile_X { ... }` block of the SDK.
sdk_const() { # profile module name
  local profile="$1" name="$2"
  awk -v p="mod $profile" -v n="const $name: usize" '
    index($0, p) { inside = 1 }
    inside && index($0, n) { sub(/.*= */, ""); sub(/;.*/, ""); print; exit }
    inside && /^}/ { inside = 0 }
  ' "$SDK"
}

# const NAME: usize = N; guarded by a target cfg on the line above.
# `arch` is "aarch64" or "other"; falls back to an unguarded definition.
wave_const() { # file name arch
  local file="$1" name="$2" arch="$3"
  awk -v n="const $name: usize" -v a="$arch" '
    /^#\[cfg\(target_arch = "aarch64"\)\]/ { guard = "aarch64"; next }
    /^#\[cfg\(not\(target_arch = "aarch64"\)\)\]/ { guard = "other"; next }
    index($0, n) {
      val = $0; sub(/.*= */, "", val); sub(/;.*/, "", val)
      if (guard == a) { print val; exit }
      if (guard == "") { unguarded = val }
      guard = ""
      next
    }
    { guard = "" }
    END { if (unguarded != "") print unguarded }
  ' "$file"
}


H2="$ROOT/modules/foundation/http/server/h2.rs"
H3="$ROOT/modules/foundation/http/server/h3.rs"
HTTP="$ROOT/modules/foundation/http/server/mod.rs"

render() {
  cat <<EOF
# Connection envelope

Generated by \`tools/ci/envelope_table.sh --write\` from the constants that
compile the path; \`fluxor ci\` fails when this file and the constants
disagree. Do not edit the tables by hand.

The effective envelope is the SMALLEST ceiling on the path, which is rarely
the layer being asked about. On aarch64 the HTTP slot and arena tables bound
HTTPS concurrency, far below the transport underneath them; on rp2350 the TLS
session, HTTP slot and arena tables all hold four.

## Per target

| Layer | Constant | aarch64 (Pi 5, Linux host) | rp2350 | Owner | One past it |
|---|---|---|---|---|---|
| TCP connections | \`ip::MAX_TCP_CONNS\` | $(sdk_const profile_host MAX_TCP_CONNS) | $(sdk_const profile_embedded MAX_TCP_CONNS) | Fluxor profile constant | SYN unanswered |
| TLS sessions | \`tls::MAX_SESSIONS\` | $(sdk_const profile_host MAX_SESSIONS) | $(sdk_const profile_embedded MAX_SESSIONS) | Fluxor profile constant | accepted conn closed, \`[tls] no session slot\` |
| HTTP slots | \`http::MAX_CONCURRENT_CONNS\` | $(sdk_const profile_host MAX_CONCURRENT_CONNS) | $(sdk_const profile_embedded MAX_CONCURRENT_CONNS) | Fluxor profile constant | idle keepalive evicted, else accept closed (\`conns_refused_slots\`) |
| HTTP arena working set | \`http::ARENA_WORKING_SET_CONNS\` | $(sdk_const profile_host ARENA_WORKING_SET_CONNS) | $(sdk_const profile_embedded ARENA_WORKING_SET_CONNS) | Fluxor profile constant | accept closed (\`conns_refused_arena\`) |
| HTTP receive buffer / conn | \`http::RECV_BUF_SIZE\` | $(sdk_const profile_host RECV_BUF_SIZE) | $(sdk_const profile_embedded RECV_BUF_SIZE) | Fluxor profile constant | demux stalls (\`demux_stalls\`) |
| h2 streams / connection | \`h2::MAX_STREAMS\` | $(wave_const "$H2" MAX_STREAMS aarch64) | $(wave_const "$H2" MAX_STREAMS other) | Wave | REFUSED_STREAM (\`h2_streams_refused\`) |
| QUIC connections | \`quic::MAX_CONNS\` | $(sdk_const profile_host MAX_CONNS) | $(sdk_const profile_embedded MAX_CONNS) | Fluxor profile constant | stateless CONNECTION_REFUSED |
| h3 sessions | \`MAX_H3_SESSIONS\` | $(wave_const "$H3" MAX_H3_SESSIONS aarch64) | $(wave_const "$H3" MAX_H3_SESSIONS other) | Wave | session closed H3_REQUEST_REJECTED |
| h3 request streams (all sessions) | \`MAX_H3_STREAMS\` | $(wave_const "$H3" MAX_H3_STREAMS aarch64) | $(wave_const "$H3" MAX_H3_STREAMS other) | Wave | stream refused |
| h3 peer uni streams / session | \`MAX_PEER_UNI\` | $(wave_const "$H3" MAX_PEER_UNI aarch64) | $(wave_const "$H3" MAX_PEER_UNI other) | Wave | H3_STREAM_CREATION_ERROR |

## Lifetime limits (http parameters, milliseconds, 0 = off)

| Waiting for | Parameter | Default |
|---|---|---|
| a complete request head | \`header_timeout_ms\` | 10000 |
| the next request on a keepalive | \`keepalive_idle_ms\` | 60000 |
| the same, once the slot table is three quarters full | \`pressure_idle_ms\` | 2000 |
| bytes to move mid-request | \`stall_ms\` | 15000 |
| a WebSocket frame | \`ws_idle_ms\` | 0 |

See \`modules/foundation/http/README.md\` "Connection lifetime" for what each
one closes and which counter it charges.
EOF
}

if [[ "$MODE" == "--write" ]]; then
  mkdir -p "$(dirname "$DOC")"
  render > "$DOC"
  echo "envelope_table: wrote $DOC"
  exit 0
fi

if [[ ! -f "$DOC" ]]; then
  echo "envelope_table: $DOC missing — run with --write" >&2
  exit 1
fi
if ! diff -u "$DOC" <(render); then
  echo "envelope_table: docs/reference/envelope.md is stale — run tools/ci/envelope_table.sh --write" >&2
  exit 1
fi
echo "envelope_table: ok"
